export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CONTENT_LOADING = 'CONTENT_LOADING';
export const GET_CONTENT = 'GET_CONTENT';

export const GET_CONTENT_BY_ID = 'GET_CONTENT_BY_ID';
export const GET_COMMENT_REPLIES = 'GET_COMMENT_REPLIES';

export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
